FROM golang:1.24 AS builder


WORKDIR /app

COPY . .

RUN GOOS=linux CGO_ENABLED=0 GO_ARCH=amd64 go build -a -o main ./cmd/api


FROM scratch

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 3000

ENTRYPOINT ["/app/main"]